name: test.js CI

on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm test
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install slither-analyzer
      - run: slither --version
      - run: slither . --filter-paths="node_modules/@openzeppelin"  --exclude-dependencies